### ISSUE TITLE
在ubuntu18.04里面编译有各种问题啊，最终也没build成功，请问webpack的版本是多少？

### ISSUE THREAD

**Issue by JoneJay** [Jrohy/trojan-web#17]
在vps里执行npm install直接断网了，试了好几次都这样。
在自己虚拟机里面也是各种问题，前面必须把nodejs和npm升到最新版本才能往后走，但是到了最后一步又报错
npm Error: Rule can only have one resource source
谷歌说webpack版本太高了，但是想卸载新版本又卸不了，有人说要在package.json里指定webpack版本，请问这个版本是lock里面的4.0.0吗？？那怎么卸载新的呢。。。。。感觉进入了死循环啊。
另外npm的版本是多少？是apt install直接装的吗？？

**Comment by Jrohy** [comment]
用这个来一键安装https://github.com/Jrohy/nodejs-install， 安装长期支持版就行

**Comment by JoneJay** [comment]
> 用这个来一键安装https://github.com/Jrohy/nodejs-install ， 安装长期支持版就行

刚才重新删除再执行可以了，原因应该是没有设置淘宝源的问题，因为我之前挂的代理就没有设置淘宝

另外问一下，是要把build出来的dist文件夹下的东西，放到trojan项目的web/templates目录里面吗？谢谢。

**Comment by Jrohy** [comment]
对的

**Comment by JoneJay** [comment]
> 对的

试了之后运行还是不行，还是返回404。
好像没给编进去啊，因为文件大小还是跟之前不成功的大小差不多，才14M，看你的trojan文件有14.5M。
确定文件都放在那个目录里面了。

web后台的打印：
GET      "/favicon.ico"

**Comment by Jrohy** [comment]
编译前要运行packr2的，你看下build.sh脚本https://github.com/Jrohy/trojan/blob/master/build.sh

**Comment by Jrohy** [comment]
因为要将前端静态文件打包进去编译文件里面

**Comment by JoneJay** [comment]
> 因为要将前端静态文件打包进去编译文件里面

刚才build前运行了，是按那个脚本来的，一会我把整个目录清空再clone来一遍试试吧。

**Comment by JoneJay** [comment]
> 编译前要运行packr2的，你看下build.sh脚本https://github.com/Jrohy/trojan/blob/master/build.sh

把之前的东西都删了重新执行的还是不行，还是没打进去。是不是build的时候还有其他参数？感觉默认不会把web的东西打进去啊。我的packr2是用snap安装的

**Comment by Jrohy** [comment]
没试过用snap，都是直接用go安装的

**Comment by JoneJay** [comment]
> 没试过用snap，都是直接用go安装的

终于打进去了，应该是snap装的版本不对，因为ubuntu直接提示的用snap装，版本是2.8.0，但是go get ./...的依赖中是
trojan/pkg/mod/github.com/gobuffalo/packr/v2@v2.8.1/packr2 
是2.8.1，后来下了2.8.1装上后再build就可以了，哎，这个东西也没个提示。
谢谢了！
