### ISSUE TITLE
登录优化

### ISSUE THREAD

**Issue by Ayerss** [Jrohy/trojan-web#19]
登录页面希望不要直接修改loginForm中的值，
`this.loginForm.password = CryptoJS.SHA224(this.loginForm.password).toString()`
不然浏览器的保存密码保存下来的是加密过后的密码，register.vue同理
[login.vue](https://github.com/Jrohy/trojan-web/blob/a7d7a4faa3cc0b000909121509e52780a1ec1ed3/src/views/login/login.vue#L108)

**Comment by Jrohy** [comment]
新版已修复

**Comment by Ayerss** [comment]
感谢大佬

**Comment by ThonyDroidYT** [comment]
你好兄弟。 由于我会说西班牙语，因此我想帮助您将Trojan项目翻译成西班牙语或英语，这使我很难用中文理解。 我仍然知道这两种语言，因此我可以帮助将其翻译成西班牙语或英语。

**Comment by ThonyDroidYT** [comment]
你好兄弟。 由于我会说西班牙语，因此我想帮助您将Trojan项目翻译成西班牙语或英语，这使我很难用中文理解。 我仍然知道这两种语言，因此我可以帮助将其翻译成西班牙语或英语。

**Comment by Jrohy** [comment]
@ThonyDroidYT https://github.com/Jrohy/trojan-web/tree/master/src/lang 你可以参考这里加下xx.js，然后提个pr
