### ISSUE TITLE
发现一个登录bug

### ISSUE THREAD

**Issue by ihuale** [Jrohy/trojan-web#22]
复现步骤：
1. 创建一个vps，然后使用trojan-install一键脚本配置
2. 访问web管理界面，设置密码，chrome记住密码
3. 销毁或者关闭第一个vps，重新创建新的vps并配置trojan-install，与第一个vps一样绑定同一个域名
4. 访问web管理界面   

问题出现在第四步，不需要配置密码即可进入web管理页面。
清除掉chrome的缓存之后再进入web管理页面才会出现第一次登录需要配置密码提示

**Comment by Jrohy** [comment]
确实有这个问题，后面会修复下

**Comment by Jrohy** [comment]
2.10.7版本已修复，感谢反馈
