### ISSUE TITLE
能不能加一个复制clash链接的功能呢？感谢！

### ISSUE THREAD

**Issue by zxkmm** [Jrohy/trojan-web#43]
``导入到clash``按钮在Linux下用不了。感谢！

**Comment by Jrohy** [comment]
新版已添加

**Comment by hrkkid** [comment]
> 新版已添加

大佬，新版的clash链接，https后面出现了两个分号，删除一个分号才能正常使用链接。

**Comment by Jrohy** [comment]
@hrkkid 确实有这个问题，谢谢提醒, 今天修复
