### ISSUE TITLE
如何自定义前端页面?

### ISSUE THREAD

**Issue by libinghope** [Jrohy/trojan-web#45]
你好,我看你是把前端的静态页面和程序一起打了包, 那我想自己手动修改前端页面(我懂一点vue),应该如何操作呢?

**Comment by Jrohy** [comment]
自己打包编译， 参考下仓库jrohy/trojan仓库的编译脚本

**Comment by zhihao-infstones** [comment]
Hi Jrohy, 你好

我也想改前端用户的页面， 但是我看你的脚本里，是页面和程序一起打包， 然后下下来运行的， 
https://github.com/Jrohy/trojan/blob/master/install.sh

请问我只想改 前端的页面 https://github.com/Jrohy/trojan-web
这样需要怎样做才能只能前端的页面

多谢

**Comment by libinghope** [comment]
@zhihao-infstones  最佳策略：原版torjan + nginx + 自己开发的前端页面
