### ISSUE TITLE
请问config文件的路径是什么

### ISSUE THREAD

**Issue by qiangxinglin** [Jrohy/trojan-web#5]
请问后端db的host, port等config文件路径是什么?

**Comment by Jrohy** [comment]
查看下trojan配置文件: /usr/local/etc/trojan/config.json

**Comment by qiangxinglin** [comment]
是在哪个文件里读取的? 我找了半天没找到是怎么读取的配置

**Comment by Jrohy** [comment]
就是读取trojan配置文件的

**Comment by qiangxinglin** [comment]
另外我看你后端的table scheme比官方要求的多了一列, 是因为前端要显示密码的原因么?

**Comment by Jrohy** [comment]
是的，要显示原始密码

**Comment by qiangxinglin** [comment]
我可以使用官方trojan+你的前端进行密码管理么? 
我在自己试着用docker做一个一键懒人包, 你的docker必须要bash进去init, 我想能不能直接mount config file进去?

**Comment by Jrohy** [comment]
不行的，前端对接了后台

**Comment by Jrohy** [comment]
主要是制作镜像的时候没权限操作systemctl, 得运行容器的时候授权了，进去容器才能进行systemctl 相关操作

**Comment by qiangxinglin** [comment]
我的想法是单独把acme摘出来, 自行续签泛域名cert, 443端口给nginx做SNI 4层转发, 然后trojan监听非443端口.
把db, trojan后端, trojan-web前端都分离开, 用compose做. 这样就不用systemctl.
毕竟穷😳, 一个服务器混合用
