### ISSUE TITLE
【BUG】于用户管理页手动删除所有用户后，会错误地提示链接mysql失败

### ISSUE THREAD

**Issue by ichig0xf** [Jrohy/trojan-web#6]
![image](https://user-images.githubusercontent.com/68801289/89020570-b888b480-d351-11ea-8f6d-fe0495f1a311.png)
错误提示如图，在用户管理页手动删除所有用户后，会错误地出现该提示。
实际上数据库链接正常，且于该页面手动添加一个用户后即可回复正常。
个人猜测是判断逻辑出了点问题。

**Comment by Jrohy** [comment]
后台返回数据逻辑有问题

**Comment by Jrohy** [comment]
2.8.4版本已修复, 更新下
